[package]
name    = "myterm_ui"
version.workspace = true
edition.workspace = true

[dependencies]
myterm_core     = { workspace = true }
myterm_pty      = { workspace = true }
myterm_vte      = { workspace = true }
myterm_settings = { workspace = true }
myterm_features = { workspace = true }
feature_git       = { workspace = true }
feature_suggest   = { workspace = true }
feature_jump      = { workspace = true }
feature_highlight = { workspace = true }
feature_fzf       = { workspace = true }
feature_predict   = { workspace = true }
egui            = { workspace = true }
eframe          = { workspace = true }
anyhow          = { workspace = true }
fuzzy-matcher   = { workspace = true }
vte             = { workspace = true }
directories     = { workspace = true }
serde_json      = { workspace = true }
